import { createFileRoute, useServerFn } from "@tanstack/react-router";
import { useState } from "react";
import { detectAiText } from "../lib/ai-tools.functions";

export const Route = createFileRoute("/tools/detector")({
  head: () => ({
    meta: [
      { title: "AI Detector — Check if text is AI-generated" },
      {
        name: "description",
        content:
          "Estimate whether text was written by a human or generated by AI, with a probability score and reasoning.",
      },
      { property: "og:title", content: "AI Detector" },
      {
        property: "og:description",
        content: "Check whether text was written by a human or AI.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary" },
    ],
  }),
  component: DetectorPage,
});

type Result = { aiScore: number; verdict: string; reasons: string[] };

function DetectorPage() {
  const detect = useServerFn(detectAiText);
  const [input, setInput] = useState("");
  const [result, setResult] = useState<Result | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function onSubmit() {
    if (!input.trim()) return;
    setLoading(true);
    setError(null);
    setResult(null);
    try {
      const res = await detect({ data: { text: input.trim() } });
      setResult(res);
    } catch (e) {
      const msg = e instanceof Error ? e.message : "Something went wrong";
      setError(msg.includes("402") ? "AI credits khatam ho gaye." : msg.includes("429") ? "Rate limit. Thodi der baad try karein." : msg);
    } finally {
      setLoading(false);
    }
  }

  const score = result?.aiScore ?? 0;
  const barColor =
    score >= 70 ? "bg-red-500" : score >= 40 ? "bg-amber-500" : "bg-emerald-500";

  return (
    <div>
      <h1 className="font-[family-name:var(--font-serif)] text-4xl md:text-5xl leading-tight tracking-tight">
        AI Detector
      </h1>
      <p className="mt-3 text-muted-foreground">
        Check karein ki text human ne likha hai ya AI ne generate kiya hai.
      </p>

      <div className="mt-8 space-y-3">
        <label className="text-xs uppercase tracking-[0.2em] text-muted-foreground">
          Text to analyze
        </label>
        <textarea
          value={input}
          onChange={(e) => setInput(e.target.value)}
          rows={8}
          placeholder="Paste text to check..."
          className="w-full resize-y rounded-md border border-border bg-background p-4 text-sm outline-none focus:border-foreground/40 transition"
        />
        <div className="flex items-center justify-between">
          <span className="text-xs text-muted-foreground">
            {input.length} / 8000
          </span>
          <button
            onClick={onSubmit}
            disabled={loading || !input.trim()}
            className="inline-flex items-center justify-center rounded-md bg-primary px-5 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 disabled:opacity-50"
          >
            {loading ? "Analyzing..." : "Detect"}
          </button>
        </div>
      </div>

      {error && (
        <p className="mt-6 rounded-md border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">
          {error}
        </p>
      )}

      {result && (
        <div className="mt-8 rounded-md border border-border p-6">
          <div className="flex items-baseline justify-between">
            <div>
              <div className="text-xs uppercase tracking-[0.2em] text-muted-foreground">
                Verdict
              </div>
              <div className="mt-1 font-[family-name:var(--font-serif)] text-3xl">
                {result.verdict}
              </div>
            </div>
            <div className="text-right">
              <div className="text-xs uppercase tracking-[0.2em] text-muted-foreground">
                AI Score
              </div>
              <div className="mt-1 font-[family-name:var(--font-serif)] text-3xl tabular-nums">
                {result.aiScore}%
              </div>
            </div>
          </div>
          <div className="mt-4 h-2 w-full overflow-hidden rounded-full bg-muted">
            <div
              className={`h-full ${barColor} transition-all`}
              style={{ width: `${Math.min(100, Math.max(0, score))}%` }}
            />
          </div>
          {result.reasons?.length > 0 && (
            <ul className="mt-6 space-y-2 text-sm text-muted-foreground">
              {result.reasons.map((r, i) => (
                <li key={i} className="flex gap-2">
                  <span className="text-foreground">·</span>
                  <span>{r}</span>
                </li>
              ))}
            </ul>
          )}
        </div>
      )}
    </div>
  );
}
