/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSeoRouteImport } from './routes/app.seo'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppPlagiarismRouteImport } from './routes/app.plagiarism'
import { Route as AppKeywordsRouteImport } from './routes/app.keywords'
import { Route as AppHumanizerRouteImport } from './routes/app.humanizer'
import { Route as AppDetectorRouteImport } from './routes/app.detector'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAiWriterRouteImport } from './routes/app.ai-writer'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSeoRoute = AppSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppPlagiarismRoute = AppPlagiarismRouteImport.update({
  id: '/plagiarism',
  path: '/plagiarism',
  getParentRoute: () => AppRoute,
} as any)
const AppKeywordsRoute = AppKeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => AppRoute,
} as any)
const AppHumanizerRoute = AppHumanizerRouteImport.update({
  id: '/humanizer',
  path: '/humanizer',
  getParentRoute: () => AppRoute,
} as any)
const AppDetectorRoute = AppDetectorRouteImport.update({
  id: '/detector',
  path: '/detector',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiWriterRoute = AppAiWriterRouteImport.update({
  id: '/ai-writer',
  path: '/ai-writer',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/ai-writer': typeof AppAiWriterRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/detector': typeof AppDetectorRoute
  '/app/humanizer': typeof AppHumanizerRoute
  '/app/keywords': typeof AppKeywordsRoute
  '/app/plagiarism': typeof AppPlagiarismRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/seo': typeof AppSeoRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/ai-writer': typeof AppAiWriterRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/detector': typeof AppDetectorRoute
  '/app/humanizer': typeof AppHumanizerRoute
  '/app/keywords': typeof AppKeywordsRoute
  '/app/plagiarism': typeof AppPlagiarismRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/seo': typeof AppSeoRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/ai-writer': typeof AppAiWriterRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/detector': typeof AppDetectorRoute
  '/app/humanizer': typeof AppHumanizerRoute
  '/app/keywords': typeof AppKeywordsRoute
  '/app/plagiarism': typeof AppPlagiarismRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/seo': typeof AppSeoRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/app/ai-writer'
    | '/app/analytics'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/detector'
    | '/app/humanizer'
    | '/app/keywords'
    | '/app/plagiarism'
    | '/app/projects'
    | '/app/seo'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/app/ai-writer'
    | '/app/analytics'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/detector'
    | '/app/humanizer'
    | '/app/keywords'
    | '/app/plagiarism'
    | '/app/projects'
    | '/app/seo'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/app/ai-writer'
    | '/app/analytics'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/detector'
    | '/app/humanizer'
    | '/app/keywords'
    | '/app/plagiarism'
    | '/app/projects'
    | '/app/seo'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/seo': {
      id: '/app/seo'
      path: '/seo'
      fullPath: '/app/seo'
      preLoaderRoute: typeof AppSeoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plagiarism': {
      id: '/app/plagiarism'
      path: '/plagiarism'
      fullPath: '/app/plagiarism'
      preLoaderRoute: typeof AppPlagiarismRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/keywords': {
      id: '/app/keywords'
      path: '/keywords'
      fullPath: '/app/keywords'
      preLoaderRoute: typeof AppKeywordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/humanizer': {
      id: '/app/humanizer'
      path: '/humanizer'
      fullPath: '/app/humanizer'
      preLoaderRoute: typeof AppHumanizerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/detector': {
      id: '/app/detector'
      path: '/detector'
      fullPath: '/app/detector'
      preLoaderRoute: typeof AppDetectorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-writer': {
      id: '/app/ai-writer'
      path: '/ai-writer'
      fullPath: '/app/ai-writer'
      preLoaderRoute: typeof AppAiWriterRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiWriterRoute: typeof AppAiWriterRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDetectorRoute: typeof AppDetectorRoute
  AppHumanizerRoute: typeof AppHumanizerRoute
  AppKeywordsRoute: typeof AppKeywordsRoute
  AppPlagiarismRoute: typeof AppPlagiarismRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppSeoRoute: typeof AppSeoRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiWriterRoute: AppAiWriterRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDetectorRoute: AppDetectorRoute,
  AppHumanizerRoute: AppHumanizerRoute,
  AppKeywordsRoute: AppKeywordsRoute,
  AppPlagiarismRoute: AppPlagiarismRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppSeoRoute: AppSeoRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
